apiVersion: v1
kind: Service
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: test-app
  ports:
    - port: 8100          # port exposed outside ClusterIP
      targetPort: 8100    # port exposed by Pod